Importação de bibliotecas e dataset

In [13]:
#importando bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
#leitura do dataset
#transformando df para utf-8
converter = pd.read_csv(r'..\data\raw\Sample - Superstore.csv', encoding="latin1")
converter.to_csv(r'..\data\intermin\arquivo_utf8.csv', index=False, encoding="utf-8")

In [15]:
df_base = pd.read_csv(r'..\data\intermin\arquivo_utf8.csv')
df_base.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

Tratamento e Limpeza de Dados

In [16]:
#realizando alterações em cópia do dataframe
df = df_base.copy()

In [17]:
##renomeando colunas
df.columns = df.columns.str.lower()
df.columns = df.columns.str.lower().str.replace(' ', '_')
df.columns = df.columns.str.lower().str.replace('-', '_')
df.columns = df.columns = df.columns.str.strip()
df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub_category',
       'product_name', 'sales', 'quantity', 'discount', 'profit'],
      dtype='str')

In [18]:
#removendo coluna row_id
df = df.drop('row_id', axis = 1)
df.head()

,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,state,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [19]:
#verificando tipos de dados
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       9994 non-null   str
 1   order_date     9994 non-null   str
 2   ship_date      9994 non-null   str
 3   ship_mode      9994 non-null   str
 4   customer_id    9994 non-null   str
 5   customer_name  9994 non-null   str
 6   segment        9994 non-null   str
 7   country        9994 non-null   str
 8   city           9994 non-null   str
 9   state          9994 non-null   str
 10  postal_code    9994 non-null   int64
 11  region         9994 non-null   str
 12  product_id     9994 non-null   str
 13  category       9994 non-null   str
 14  sub_category   9994 non-null   str
 15  product_name   9994 non-null   str
 16  sales          9994 non-null   float64
 17  quantity       9994 non-null   int64
 18  discount       9994 non-null   float64
 19  profit         9994 non-null   float64
dtypes: float64(3), int64(2), str(15)
memory usage: 1.5 MB

In [20]:
#converter datas para datetime
for col in ["order_date", "ship_date"]:
    df[col] = pd.to_datetime(df[col], format="%m/%d/%Y")

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       9994 non-null   str
 1   order_date     9994 non-null   datetime64[us]
 2   ship_date      9994 non-null   datetime64[us]
 3   ship_mode      9994 non-null   str
 4   customer_id    9994 non-null   str
 5   customer_name  9994 non-null   str
 6   segment        9994 non-null   str
 7   country        9994 non-null   str
 8   city           9994 non-null   str
 9   state          9994 non-null   str
 10  postal_code    9994 non-null   int64
 11  region         9994 non-null   str
 12  product_id     9994 non-null   str
 13  category       9994 non-null   str
 14  sub_category   9994 non-null   str
 15  product_name   9994 non-null   str
 16  sales          9994 non-null   float64
 17  quantity       9994 non-null   int64
 18  discount       9994 non-null   float64
 19  profit         9994 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(2), str(13)
memory usage: 1.5 MB

In [22]:
#análise de duplicatas e valores nulos
#valores nulos
df.isnull().sum()

order_id         0
order_date       0
ship_date        0
ship_mode        0
customer_id      0
customer_name    0
segment          0
country          0
city             0
state            0
postal_code      0
region           0
product_id       0
category         0
sub_category     0
product_name     0
sales            0
quantity         0
discount         0
profit           0
dtype: int64

In [23]:
df[df.duplicated(subset=["order_id", "product_id"])]

,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,state,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
352,CA-2016-129714,2016-09-01,2016-09-03,First Class,AB-10060,Adam Bellavance,Home Office,United States,New York City,New York,10009,East,OFF-PA-10001970,Office Supplies,Paper,Xerox 1881,49.120,4,0.0,23.0864
431,US-2016-123750,2016-04-15,2016-04-21,Standard Class,RB-19795,Ross Baird,Home Office,United States,Gastonia,North Carolina,28052,South,TEC-AC-10004659,Technology,Accessories,Imation Secure+ Hardware Encrypted USB 2.0 Fla...,291.960,5,0.2,54.7425
1301,CA-2016-137043,2016-12-23,2016-12-25,Second Class,LC-17140,Logan Currie,Consumer,United States,Springfield,Virginia,22153,South,FUR-FU-10003664,Furniture,Furnishings,"Electrix Architect's Clamp-On Swing Arm Lamp, ...",286.380,3,0.0,83.0502
3184,CA-2017-152912,2017-11-09,2017-11-12,Second Class,BM-11650,Brian Moss,Corporate,United States,Columbia,Maryland,21044,East,OFF-ST-10003208,Office Supplies,Storage,Adjustable Depth Letter/Legal Cart,544.380,3,0.0,157.8702
3406,US-2014-150119,2014-04-23,2014-04-27,Standard Class,LB-16795,Laurel Beltran,Home Office,United States,Columbus,Ohio,43229,East,FUR-CH-10002965,Furniture,Chairs,Global Leather Highback Executive Chair with P...,281.372,2,0.3,-12.0588
6500,CA-2015-103135,2015-07-24,2015-07-28,Standard Class,SS-20515,Shirley Schmidt,Home Office,United States,Louisville,Kentucky,40214,South,OFF-BI-10000069,Office Supplies,Binders,"GBC Prepunched Paper, 19-Hole, for Binding Sys...",90.060,6,0.0,41.4276
7882,CA-2017-118017,2017-12-03,2017-12-06,Second Class,LC-16870,Lena Cacioppo,Consumer,United States,Thornton,Colorado,80229,West,TEC-AC-10002006,Technology,Accessories,Memorex Micro Travel Drive 16 GB,102.336,8,0.2,14.0712
9169,CA-2016-140571,2016-03-15,2016-03-19,Standard Class,SJ-20125,Sanjit Jacobs,Home Office,United States,Jackson,Mississippi,39212,South,OFF-PA-10001954,Office Supplies,Paper,Xerox 1964,45.680,2,0.0,21.0128

In [24]:
df.duplicated().sum()

np.int64(1)

In [25]:
# Foi verificada duplicidade considerando order_id e product_id.
# Embora existam múltiplas ocorrências dessa combinação, a maioria apresenta diferenças em métricas como discount, quantity ou profit, indicando que representam transações distintas dentro do mesmo pedido.
# Apenas uma duplicata exata foi identificada

In [26]:
#removendo duplicatas
df = df.drop_duplicates()
df.info()

<class 'pandas.DataFrame'>
Index: 9993 entries, 0 to 9993
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       9993 non-null   str
 1   order_date     9993 non-null   datetime64[us]
 2   ship_date      9993 non-null   datetime64[us]
 3   ship_mode      9993 non-null   str
 4   customer_id    9993 non-null   str
 5   customer_name  9993 non-null   str
 6   segment        9993 non-null   str
 7   country        9993 non-null   str
 8   city           9993 non-null   str
 9   state          9993 non-null   str
 10  postal_code    9993 non-null   int64
 11  region         9993 non-null   str
 12  product_id     9993 non-null   str
 13  category       9993 non-null   str
 14  sub_category   9993 non-null   str
 15  product_name   9993 non-null   str
 16  sales          9993 non-null   float64
 17  quantity       9993 non-null   int64
 18  discount       9993 non-null   float64
 19  profit         9993 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(2), str(13)
memory usage: 1.6 MB

In [27]:
#padronizando nome des de colunas
cols_texto = ['customer_name', 'city', 'state'] 
for col in cols_texto: 
    df[col] = df[col].str.strip().str.title()
df.head()

,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,state,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

Criação de Colunas Derivadas

In [28]:
#prazo de entrega - período do pedido até a data do envio
df['data_entrega'] = (df['ship_date'] - df['order_date']).dt.days

In [29]:
#componentes temporais com relação a data do pedido
df['ano'] = df['order_date'].dt.year
df['mes'] = df['order_date'].dt.month
df['trimestre'] = df['order_date'].dt.quarter

In [30]:
#margem de lucro por venda
df['margem_pct'] = (df['profit']/df['sales']).round(4)

In [31]:
#ticket médio por pedido
ticket = df.groupby('order_id')['sales'].sum().reset_index()
ticket.columns = ['order_id', 'ticket_medio']
df = df.merge(ticket, on ='order_id', how='left')

In [32]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,state,...,sales,quantity,discount,profit,data_entrega,ano,mes,trimestre,margem_pct,ticket_medio
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,...,261.9600,2,0.00,41.9136,3,2016,11,4,0.1600,993.9000
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,...,731.9400,3,0.00,219.5820,3,2016,11,4,0.3000,993.9000
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,...,14.6200,2,0.00,6.8714,4,2016,6,2,0.4700,14.6200
3,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,...,957.5775,5,0.45,-383.0310,7,2015,10,4,-0.4000,979.9455
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,...,22.3680,2,0.20,2.5164,7,2015,10,4,0.1125,979.9455

Exportando o csv

In [33]:
# Salvar dataset tratado 
df.to_csv(r'..\data\processed\superstore_limpo.csv', index=False, encoding='utf-8-sig')